# Generated by Django 5.1.7 on 2025-03-20 15:35

from django.db import migrations, models

import apps.short_urls.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(default=apps.short_urls.utils.generate_random_string, max_length=8, unique=True)),
            ],
        ),
    ]
